

import {
  Plant, PlantInput, TextRange, HardinessZones, ToxicityDetail, ToxicityInformation,
  AirTemperatureCelsius, RelativeHumidityPercentage, LightIntensityLux, PlacementSpacing,
  GrowthStageTimelineEntry, PlantIdentificationOverview
} from '../types';

// This function is similar to the one previously in App.tsx,
// but now it's a standalone utility.
export const createDefaultPlantStructureInternal = (input: PlantInput): Omit<Plant, 'id' | 'created_at' | 'updated_at'> => {
    const now = new Date().toISOString();
    const commonName = input.common_name;
    const defaultTextVal = "Not yet specified";
    const defaultNum = 0; 
    const defaultTextRange: TextRange = { min: null, max: null, text_range: defaultTextVal };
    const defaultHardiness: HardinessZones = { usda: null, rhs: null, other_system_specify: null };
    const defaultToxicity: ToxicityDetail = { level: 'Unknown', details: null };
    const defaultToxInfo: ToxicityInformation = { human_toxicity: defaultToxicity, dog_toxicity: defaultToxicity, cat_toxicity: defaultToxicity, other_animal_toxicity_specify: null };
    
    const defaultAirTemp: AirTemperatureCelsius = { daytime_optimal_min: defaultNum, daytime_optimal_max: defaultNum, nighttime_optimal_min: defaultNum, nighttime_optimal_max: defaultNum, absolute_survival_min: defaultNum, absolute_survival_max: defaultNum, notes: defaultTextVal };
    const defaultHumidity: RelativeHumidityPercentage = { optimal_min: defaultNum, optimal_max: defaultNum, absolute_min: defaultNum, absolute_max: defaultNum, notes: defaultTextVal };
    const defaultLightIntensity: LightIntensityLux = { seedling_optimal_min: null, seedling_optimal_max: null, mature_plant_optimal_min: null, mature_plant_optimal_max: null, notes: defaultTextVal };
    const defaultPlacement: PlacementSpacing = { best_placement_indoors: null, best_placement_outdoors: null, recommended_planting_spacing_meters: null };

    const defaultGrowthStageEntry: GrowthStageTimelineEntry = { expected_min_days: defaultNum, expected_max_days: defaultNum, optimal_average_days: defaultNum, event_description_notes: defaultTextVal };

    const plantIdentificationOverview: PlantIdentificationOverview = {
        common_names: [commonName],
        latin_name_scientific_name: input.scientific_name || defaultTextVal,
        plant_family: input.family || defaultTextVal,
        plant_type_category: input.plant_type_category || defaultTextVal,
        description_brief: input.description_brief || "Awaiting detailed description.",
        cultivar_variety: null,
        growth_structure_habit: defaultTextVal,
        expected_mature_height_meters: defaultTextRange,
        expected_mature_spread_width_meters: defaultTextRange,
        life_cycle: defaultTextVal,
        native_regions: [],
        hardiness_zones: defaultHardiness,
    };

    // Note: 'id' will be generated by Supabase, 'created_at' and 'updated_at' also handled by DB.
    // This structure now matches the cleaned 'Plant' type.
    return {
        display_image_url: input.display_image_url || null, // Initial value, will be processed by service
        image_object_position_y: input.image_object_position_y || 50, // Default to 50 (center)
        plant_identification_overview: plantIdentificationOverview,
        key_features_uses_general: {
            primary_uses: [],
            special_distinguishing_features: [],
            toxicity_information: defaultToxInfo,
        },
        cultivation_growing_conditions: {
            light_requirements_general: { recommended_exposure: defaultTextVal, minimum_daily_light_hours_mature: null, notes_on_light_mature: null },
            water_requirements_general: { recommended_watering_frequency_moisture_level: defaultTextVal, drought_tolerance: 'Medium', watering_notes_min_max_guidance: null },
            soil_requirements_general: { preferred_soil_types: [], soil_ph_range_overall: { min: 6.0, max: 7.0, optimal: 6.5 }, soil_drainage_requirements: defaultTextVal, soil_enrichment_notes: null },
            environmental_tolerances_detailed: {
                air_temperature_celsius: defaultAirTemp,
                relative_humidity_percentage: defaultHumidity,
                light_intensity_lux: defaultLightIntensity,
                placement_spacing: defaultPlacement,
            }
        },
        plant_nutrition_fertilization_needs: {
            general_fertilizer_preferences: null,
            phase_specific_fertilization_needs: [],
        },
        plant_care_maintenance: {
            pruning_shaping: { pruning_objectives: [], best_times_for_pruning_seasonal: [], pruning_techniques_description: null, tools_recommended: [], pruning_notes_detailed: null },
            repotting_for_container_plants: null,
            root_strengthening_techniques: [],
            propagation_methods_summary: {
                primary_methods: [],
                seed_propagation_details: { is_applicable: false, brief_sowing_and_early_care_steps: [], expected_success_rate_notes: null, recommended_sowing_time_season: null, pre_germination_treatment: {soaking_seeds_details: null, scarification_details: null, stratification_details: null}, germination_requirements_detailed: { seed_depth_cm: {min:0, max:0, notes:null}, soil_temperature_celsius: {optimal_min:0, optimal_max:0, absolute_min_for_germination:0, absolute_max_for_germination:0, notes:null}, soil_mix_recommendation: defaultTextVal, soil_moisture_level_description: defaultTextVal, watering_method_germination: defaultTextVal, humidity_percentage_germination: {optimal_min:0, optimal_max:0}, light_for_germination_requirement: defaultTextVal, expected_germination_timeframe_days_range: null }, early_seedling_phase_water_management_sprout_to_8_weeks: { target_medium_moisture_level_description: null, recommended_watering_method: [], watering_frequency_guidance: null, approximate_amount_of_water_per_application: null, importance_of_good_drainage_notes: null, water_temperature_consideration_celsius: null, soil_temperature_considerations_after_watering: null, humidity_considerations_acclimation: null, signs_of_overwatering_seedlings: [], signs_of_underwatering_seedlings: [], transitioning_watering_practices_notes: null }, other_early_seedling_care_sprout_to_8_weeks: { light_requirements_for_seedlings_hours_type: null, temperature_requirements_for_seedlings_celsius: {day_min: null, day_max:null, night_min:null, night_max:null}, ventilation_needs_description: null, first_fertilization_details: null, hardening_off_procedure_within_8_weeks: null } },
                cutting_propagation_details: { is_applicable: false, cutting_types_common: [], best_time_for_cuttings_by_type: [], brief_step_by_step_overview: [], cutting_preparation_notes: null, rooting_medium_recommendations: [], environmental_conditions_for_rooting_notes: null, expected_rooting_timeframe_weeks_range: null, aftercare_once_rooted_instructions: null, expected_success_rate_notes: null, common_challenges: [] },
                grafting_propagation_details: { is_applicable: false, common_grafting_types_used: [], best_time_for_grafting_by_type: [], brief_step_by_step_overview: [], rootstock_selection_considerations: null, scion_selection_considerations: null, tools_materials_needed: [], aftercare_instructions_detailed: null, expected_success_rate_notes: null, common_challenges: [] },
            }
        },
        growth_stage_timelines_days_from_sowing: {
            sprouting: { ...defaultGrowthStageEntry },
            first_true_leaves: { ...defaultGrowthStageEntry },
            first_repotting_seedling: { ...defaultGrowthStageEntry, pot_size_increase_factor_guideline: null },
            hardening_off_start: { ...defaultGrowthStageEntry },
            transplant_outdoors_seedling: { ...defaultGrowthStageEntry },
            first_fertilization_after_true_leaves: { ...defaultGrowthStageEntry, trigger_condition: "N/A" },
            first_pruning_formative: { ...defaultGrowthStageEntry },
            flowering_start: { ...defaultGrowthStageEntry },
            first_harvest_expected: { ...defaultGrowthStageEntry },
        },
        ecological_interactions: {
            pest_interactions: { pests_attracted_to_plant: [], pests_repelled_by_plant: [] },
            disease_susceptibility: { common_diseases: [], prevention_non_chemical_treatment_notes: null },
            pest_disease_management_specific_strategies: { natural_organic_pest_control_methods: [], chemical_pest_control_options_if_necessary: [], integrated_pest_management_ipm_strategies_for_plant: null },
            companion_planting: { beneficial_companions_plants_it_aids: [], synergistic_companions_plants_that_aid_it: [], antagonistic_plants_avoid_nearby: [] },
            pollinators_wildlife_interaction: { attracts_pollinators: [], provides_food_shelter_for_wildlife: [] },
        },
        fruiting_harvesting_conditional: {
            is_applicable: false,
            flowering_pollination_for_fruit_set: { flowering_time_season: null, pollination_requirements: null, cross_pollination_partners_if_applicable_ids_names: [], techniques_to_assist_pollination: null },
            fruit_vegetable_development_enhancement: { time_from_flower_to_harvest_typical: null, techniques_to_improve_size: null, techniques_to_improve_flavor: null, techniques_to_improve_texture: null, techniques_to_improve_juice_content: null },
            harvesting_details: { harvesting_season_indicators_of_ripeness: null, harvesting_techniques: null, post_harvest_handling_storage_short_term: null },
        },
        annual_care_calendar_timeline_summary: [],
        use_cases_human_symbiosis: {
            culinary_uses: [],
            preservation_conservation_techniques_for_plant: [],
            alternative_products_uses: [],
            medicinal_uses_traditional_folk: [],
            other_craft_material_uses: [],
        },
        seed_saving_storage_details: {
            seed_viability_duration_years_optimal: null,
            harvesting_seeds_guide: { timing_indicators: null, method_selection_criteria: null },
            cleaning_drying_seeds_techniques: null,
            optimal_storage_conditions: { temperature_celsius: null, humidity_percent: null, container_type: null, other_notes: null },
            seed_viability_testing_methods_description: [],
        },
        user_sourcing_information: {
            user_notes: "Newly added plant. Consider using AI to populate details.",
            date_record_created: now, // Will be overridden by DB
            date_record_last_modified: now, // Will be overridden by DB
            information_sources: [],
            ai_query_log_if_applicable: null
        }
    };
};
